Improve style, add libre game filter
eried/ArduboyCollection pull request #35
Opened 2018-02-19 19:10 UTC by alexgleason

Hi again,

This change is untested because I could not figure out how. Please test it before merging.

I improved the CSS on the homepage to look like this:

![screenshot from 2018-02-19 14 05 02](https://user-images.githubusercontent.com/3639540/36393583-314c871e-157e-11e8-8bb6-3a08dda4256e.png)

I also included a libre game filter that only displays games with certain licenses.

Finally, if a game doesn't have a license, that makes the game proprietary, so I changed the language from "unspecified" to "proprietary" and removed the icon in that case. Hopefully Mustache works the way I expect here.

2018-02-19 20:52 UTC, eried commented
Awesome! I'll test it soon and publish it

2018-02-20 23:13 UTC, eried requested changes
There is an error with the mustache syntax. You can check the reference here: https://mustache.github.io/mustache.5.html and you can paste the `template.html` here https://mustache.github.io/#demo in the first field and http://arduboy.ried.cl/repo.json contents in the second field to test it without installing anything.

2018-02-20 23:15 UTC, eried commented on .admin/public_html/arduboy/template.html
> +									{{#license}}
[20-Feb-2018 17:04:21 America/Chicago] PHP Fatal error:  Uncaught exception 'Mustache_Exception_SyntaxException' with message 'Nesting error: license (on line 90) vs. items (on line 103)' in /home/erwinrie/public_html/arduboytest/Mustache/Parser.php:126
Stack trace:
#0 /home/erwinrie/public_html/arduboytest/Mustache/Parser.php(105): Mustache_Parser->buildTree(Array, Array)
#1 /home/erwinrie/public_html/arduboytest/Mustache/Parser.php(105): Mustache_Parser->buildTree(Array, Array)
#2 /home/erwinrie/public_html/arduboytest/Mustache/Parser.php(43): Mustache_Parser->buildTree(Array)
#3 /home/erwinrie/public_html/arduboytest/Mustache/Engine.php(745): Mustache_Parser->parse(Array)
#4 /home/erwinrie/public_html/arduboytest/Mustache/Engine.php(759): Mustache_Engine->parse('<!DOCTYPE HTML>...')
#5 /home/erwinrie/public_html/arduboytest/Mustache/Engine.php(700): Mustache_Engine->compile('<!DOCTYPE HTML>...')
#6 /home/erwinrie/public_html/arduboytest/Mustache/Engine.php(619): Mustache_Engine->loadSource('<!DOCTYPE HTML>...')
#7 /home/erwinrie/public_html/arduboytest/Mustache/ in /home/erwinrie/public_html/arduboytest/Mustache/Parser.php on line 126

2018-02-21 01:18 UTC, alexgleason commented
Okay, yes! My mustache syntax was wrong. I just force-pushed the update to this branch and tested it locally; it works.

2018-02-21 10:08 UTC, eried approved these changes

2018-02-21 10:19 UTC, eried approved these changes

2018-02-21 11:47 UTC, closed without merging

2018-02-21 11:49 UTC, eried commented
Changes were included in https://github.com/eried/ArduboyCollection/pull/36